name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            👋 Hi there! Thank you for opening your first issue in this project.  
            We appreciate your feedback and will look into it as soon as possible. 🚀

          pr-message: >
            🙌 Thanks for submitting your first pull request!  
            A maintainer will review it shortly. Welcome to the project! 🎉
